ARG PLONE_VERSION=6.0
FROM plone/server-builder:${PLONE_VERSION} as builder

WORKDIR /app

# # Add local code
# COPY . .

# Install local requirements
RUN <<EOT
    set -e
    bin/pip install plone.app.robotframework>=2.1.3
    bin/pip install 'ploneconf.site @ git+https://github.com/collective/ploneconf.site.git'
EOT


FROM plone/server-acceptance:${PLONE_VERSION}

# Copy /app from builder
COPY --from=builder /app /app

RUN <<EOT
    ln -s /data /app/var
EOT
